CREATE TABLE vms (
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL REFERENCES users(id),
	os VARCHAR(128) NOT NULL,
	ram INTEGER NOT NULL,
	disk INTEGER NOT NULL,
	cores INTEGER NOT NULL,
	created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)