CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	name VARCHAR(128) NOT NULL,
	email VARCHAR(128) NOT NULL,
	mobile VARCHAR(128) NOT NULL,
	password VARCHAR(128) NOT NULL,
	role_id INTEGER NOT NULL REFERENCES roles(id),
	created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)